version: '3.7'

services:

  postgres:
    image: postgres:latest
    ports:
    - "5444:5432"
    environment:
      POSTGRES_DB: requirement_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9999:9999"
      - "82:82"
    restart: always
    environment:
      CONFIG_PATH: ./docker-config.yaml
    volumes:
    - ./entrypoints/wait-for.sh:/root/wait-for.sh
    depends_on:
      - postgres
    command: ["./wait-for.sh", "-t", "10", "postgres:5432", "--", "./ocp-requirement-api"]

volumes:
  pgdata:
