version: '3.7'

services:

  app:
    build: .
    ports:
      - "8888:8888"
      - "9999:9999"
      - "82:82"
    restart: always
    environment:
      CONFIG_PATH: ./docker-config.yaml
    volumes:
    - ./entrypoints/wait-for.sh:/root/wait-for.sh
    depends_on:
      - postgres
    command: ["./wait-for.sh", "-t", "10", "postgres:5432", "--", "./ocp-requirement-api"]

volumes:
  pgdata:
