version: '3.7'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: requirement_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
